// <auto-generated />
using System;
using Elrakhawy.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELRakhawy.DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250827184343_AddFullWarpBeamAndRawDB")]
    partial class AddFullWarpBeamAndRawDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELRakhawy.EL.Models.FinancialTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FinancialTransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "في حالة الشراء",
                            Type = "دائن"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "في حالة البيع",
                            Type = "مدين"
                        });
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.FormStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormStyles");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.FullWarpBeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OriginYarnId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OriginYarnId");

                    b.ToTable("FullWarpBeams");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.Manufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.PackagingStyleForms", b =>
                {
                    b.Property<int>("PackagingStyleId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.HasKey("PackagingStyleId", "FormId");

                    b.HasIndex("FormId");

                    b.ToTable("PackagingStyleForms");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.PackagingStyles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PackagingStyles");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.RawItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("WarpId")
                        .HasColumnType("int");

                    b.Property<int>("WeftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarpId");

                    b.HasIndex("WeftId");

                    b.ToTable("RawItems");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderInfoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("StakeholderTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StakeholdersInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StakeholderTypeId");

                    b.HasIndex("StakeholdersInfoId");

                    b.ToTable("StakeholderInfoType");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialTransactionTypeId");

                    b.ToTable("StakeholderTypes");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderTypeForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("StakeholderTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("StakeholderTypeId");

                    b.ToTable("StakeholderTypeForms");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholdersInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StakeholderInfos");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.YarnItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginYarnId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OriginYarnId");

                    b.ToTable("YarnItems");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.YarnTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CountBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Inbound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Outbound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PackagingStyleId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StakeholderId")
                        .HasColumnType("int");

                    b.Property<int?>("StakeholderTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YarnItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PackagingStyleId");

                    b.HasIndex("StakeholderId");

                    b.HasIndex("StakeholderTypeId");

                    b.HasIndex("YarnItemId");

                    b.ToTable("YarnTransactions");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.FullWarpBeam", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.YarnItem", "OriginYarn")
                        .WithMany()
                        .HasForeignKey("OriginYarnId");

                    b.Navigation("OriginYarn");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.PackagingStyleForms", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.FormStyle", "Form")
                        .WithMany("PackagingStyleForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELRakhawy.EL.Models.PackagingStyles", "PackagingStyle")
                        .WithMany("PackagingStyleForms")
                        .HasForeignKey("PackagingStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("PackagingStyle");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.RawItem", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.FullWarpBeam", "Warp")
                        .WithMany()
                        .HasForeignKey("WarpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELRakhawy.EL.Models.YarnItem", "Weft")
                        .WithMany()
                        .HasForeignKey("WeftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warp");

                    b.Navigation("Weft");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderInfoType", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.StakeholderType", "StakeholderType")
                        .WithMany("StakeholderInfoTypes")
                        .HasForeignKey("StakeholderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELRakhawy.EL.Models.StakeholdersInfo", "StakeholdersInfo")
                        .WithMany("StakeholderInfoTypes")
                        .HasForeignKey("StakeholdersInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StakeholderType");

                    b.Navigation("StakeholdersInfo");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderType", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.FinancialTransactionType", "FinancialTransactionType")
                        .WithMany("StakeholderTypes")
                        .HasForeignKey("FinancialTransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialTransactionType");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderTypeForm", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.FormStyle", "Form")
                        .WithMany("StakeholderTypeForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELRakhawy.EL.Models.StakeholderType", "StakeholderType")
                        .WithMany("StakeholderTypeForms")
                        .HasForeignKey("StakeholderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("StakeholderType");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.YarnItem", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.Manufacturers", "Manufacturer")
                        .WithMany("YarnItems")
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("ELRakhawy.EL.Models.YarnItem", "OriginYarn")
                        .WithMany("DerivedYarns")
                        .HasForeignKey("OriginYarnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_YarnItems_OriginYarn");

                    b.Navigation("Manufacturer");

                    b.Navigation("OriginYarn");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.YarnTransaction", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.Manufacturers", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("ELRakhawy.EL.Models.PackagingStyles", "PackagingStyle")
                        .WithMany()
                        .HasForeignKey("PackagingStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELRakhawy.EL.Models.StakeholdersInfo", "Stakeholder")
                        .WithMany()
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELRakhawy.EL.Models.StakeholderType", "StakeholderType")
                        .WithMany()
                        .HasForeignKey("StakeholderTypeId");

                    b.HasOne("ELRakhawy.EL.Models.YarnItem", "YarnItem")
                        .WithMany("YarnTransactions")
                        .HasForeignKey("YarnItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("PackagingStyle");

                    b.Navigation("Stakeholder");

                    b.Navigation("StakeholderType");

                    b.Navigation("YarnItem");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.FinancialTransactionType", b =>
                {
                    b.Navigation("StakeholderTypes");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.FormStyle", b =>
                {
                    b.Navigation("PackagingStyleForms");

                    b.Navigation("StakeholderTypeForms");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.Manufacturers", b =>
                {
                    b.Navigation("YarnItems");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.PackagingStyles", b =>
                {
                    b.Navigation("PackagingStyleForms");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholderType", b =>
                {
                    b.Navigation("StakeholderInfoTypes");

                    b.Navigation("StakeholderTypeForms");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.StakeholdersInfo", b =>
                {
                    b.Navigation("StakeholderInfoTypes");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.YarnItem", b =>
                {
                    b.Navigation("DerivedYarns");

                    b.Navigation("YarnTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
