// <auto-generated />
using System;
using Elrakhawy.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELRakhawy.DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250102000000_AddFabricItemsTable")]
    partial class AddFabricItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELRakhawy.EL.Models.FabricItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OriginRawId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Item")
                        .IsUnique()
                        .HasDatabaseName("IX_FabricItems_Item_Unique");

                    b.HasIndex("OriginRawId");

                    b.ToTable("FabricItems");
                });

            modelBuilder.Entity("ELRakhawy.EL.Models.FabricItem", b =>
                {
                    b.HasOne("ELRakhawy.EL.Models.RawItem", "OriginRaw")
                        .WithMany()
                        .HasForeignKey("OriginRawId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FabricItems_RawItems");

                    b.Navigation("OriginRaw");
                });
#pragma warning restore 612, 618
        }
    }
}